version: 0.2

env:
  variables:
    AWS_ACCESS_KEY_ID: AKIAQ4BL7HTIAZXWCVP6
    AWS_SECRET_ACCESS_KEY: 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
    AWS_DEFAULT_REGION: eu-north-1

phases:
  pre_build:
    commands:
      - echo $AWS_ACCESS_KEY_ID
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 060221766864.dkr.ecr.eu-north-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t next-docker .
      - docker tag next-docker:latest 060221766864.dkr.ecr.eu-north-1.amazonaws.com/next-docker:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 060221766864.dkr.ecr.eu-north-1.amazonaws.com/next-docker:latest
      - echo Writing image definitions file...
      # - printf '[{"name":"__ECS_CONTAINER_NAME__","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
